fix(figma.utils): error now exits the process gracefully"
rangle/radius-workspace pull request #29
Opened 2022-04-13 18:49 UTC by DogaIster

The error now exits the process gracefully

Fixes # (issue)
```
script/dist/commands/styles/utils/figma.utils.js:65
        throw new Error(msg || 'Assertion failed');
              ^

Error: fileId not found
    at assert 
```
now exits gracefully with a message for the user

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2022-04-13 19:11 UTC, sumitarora requested changes

2022-04-13 19:11 UTC, sumitarora commented on packages/cli/src/commands/styles/utils/figma.utils.ts
> +  console.log('Please make sure you entered a valid URL and token and try again');
should be `logger.error`

2022-04-13 19:29 UTC, rafRangler requested changes
We need to figure out the best way to handle different errors

2022-04-14 00:36 UTC, sumitarora approved these changes

2022-04-14 00:37 UTC, sumitarora requested changes

2022-04-14 00:37 UTC, sumitarora commented on packages/cli/src/commands/styles/utils/figma.utils.ts
> +  assert(typeof fileId === 'string', 'Please put a valid URL');
`Please enter a valid URL`

2022-04-14 00:37 UTC, sumitarora commented on packages/cli/src/commands/styles/utils/figma.utils.ts
> +  assert(typeof token === 'string', 'Please put a valid token');
`Please enter a valid token`

2022-04-18 21:50 UTC, sumitarora approved these changes

2022-04-19 14:31 UTC, rafRangler approved these changes

2022-04-19 14:41 UTC, DogaIster commented on packages/cli/src/commands/styles/lib/radius-styles.ts
> +
We shouldn't need this anymore either way but let's see

2022-04-19 15:20 UTC, DogaIster commented on packages/cli/src/commands/styles/utils/figma.loader.ts
> +
not sure about this, we don't own the backend, it throws a 403 AKA 'Not Authorized', that's not the error message I am giving. I rather not confuse the user

2022-04-19 15:22 UTC, DogaIster commented on packages/cli/src/commands/styles/utils/figma.loader.ts
> +
They are different things. So, the thing is they are both in the URL
`https://www.figma.com/file/<fieldID>/Radius-Design-Kit-V2(WIP)?node-id=<node ID>`
either way it means you messed up in the URL, node ID is not something we are asking for

2022-04-19 15:51 UTC, merged